models:
  classify_model: 'source/classify-model'
  text_model: 'cl-nagoya/defsent-bert-base-uncased-cls'
  image_model: 'source/image-model'
  processor: 'source/classify-model'
  feature_extractor: 'source/image-model'

dataset: ''

parameters:
  img_weight: 0.8
  txt_weight: 0.2
  epsilon_dbscan: 0.035
  min_samples: 1